config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/search", to: "search#index"

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show destroy)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
  resources :likes, only: %i(create destroy)
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <%= t ".message" %>
    <%= pluralize object.errors.count, t(".error") %>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <%= paginate @feed_items, theme: "twitter-bootstrap-4" %>
  <ol class="microposts list-group list-group-flush">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items, theme: "twitter-bootstrap-4" %>
<% end %>

app/views/shared/_like.html.erb
<div id="like_form_<%= post.id %>">
  <%= form_for current_user.active_likes.build, remote: true do |f| %>
    <div><%= hidden_field_tag :micropost_id, post.id %></div>
    <%= f.submit t(".like"), class: "btn btn-secondary btn-sm rounded-0", id: "like" %>
  <% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group mt-2">
    <%= f.text_area :content, placeholder: t(".holder"), class: "form-control rounded-0"%>
  </div>
  <%= f.submit t(".post"), class: "btn btn-outline-primary rounded-0 btn-block mb-2" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png" %>
  </span>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag search_path, method: "get", id: "search-form" ,class: "form-inline w-50" do %>
  <%= text_field_tag :search, params[:search], class: "form-control form-control-sm rounded-0 w-75" , placeholder: t(".search") %>
  <button class="btn btn-secondary btn-sm rounded-0" type="submit">
    <i class="fa fa-fw fa-search"></i>
  </button>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path @user %>" class="btn btn-outline-primary rounded-0">
    <%= t ".following" %>
    <span class="badge badge-dark" id="following">
      <%= @user.following.count %>
    </span>
  </a>
  <a href="<%= followers_user_path @user %>" class="btn btn-outline-primary rounded-0">
    <%= t ".followers" %>
    <span class="badge badge-dark" id="followers">
      <%= @user.followers.count %>
    </span>
  </a>
</div>

app/views/shared/_unlike.html.erb
<div id="like_form_<%= post.id %>">
  <%= form_for current_user.active_likes.find_by(micropost_id: post.id), html: {method:    :delete}, remote: true do |f| %>
    <%= f.submit t(".unlike"), class: "btn btn-primary btn-sm rounded-0", id: "unlike" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<div class="row">
  <div class="col-md-2">
      <%= link_to gravatar_for(current_user, size: Settings.size), current_user %>
  </div>
  <div class="col-md-10">
    <h3>
      <%= current_user.name %>
    </h3>
    <%= link_to t(".view"), current_user %><br>
    <%= pluralize current_user.microposts.count, t(".micropost") %>
  </div>
</div>